### ISSUE TITLE
我遇到一个错误在我使用hexo g的时候

### ISSUE THREAD

**Issue by hello6060** [fan-lv/Fan#29]

**Comment by hello6060** [comment]
ERROR TypeError: /home/wwwroot/themes/Fan/layout/includes/config.pug:1
  > 1| -
    2|   var algolia = 'undefined';
    3|   var env = process.env;
    4|   if (theme.algolia_search.enable) {

Cannot read property 'valine' of undefined
    at eval (eval at wrap (/home/wwwroot/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:194:38)
    at template (eval at wrap (/home/wwwroot/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:843:72)
    at _View._compiled (/home/wwwroot/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/home/wwwroot/node_modules/hexo/lib/theme/view.js:39:17)
    at /home/wwwroot/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/home/wwwroot/node_modules/bluebird/js/release/util.js:16:23)
    at /home/wwwroot/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/wwwroot/node_modules/hexo/lib/hexo/router.js:30:5)
    at RouteStream.Readable.read (_stream_readable.js:457:10)
    at resume_ (_stream_readable.js:936:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:17) {
  path: '/home/wwwroot/themes/Fan/layout/includes/config.pug'
}

**Comment by hello6060** [comment]
我安装了需要的环境
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.0.0"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "hexo": "^5.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-json-content": "^4.2.3",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-jade": "^0.5.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-pug": "^1.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}

**Comment by fan-lv** [comment]
```
# 评论
comments:
  enable: false
  # 使用哪种评论插件["gitment", "valine"]
  type: "valine"
```
theme文件夹下面的config，设置成false就可以了，或者在最外面的config中配置一下valine的参数
